server:
  port: 8080

spring:
  appliction:
    name: Spring Security Demo
  # 当前环境设置 dev开发环境 test测试环境 prod生产环境
  profiles:
    active: dev
  # MySql 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/security-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: yuzhijie1218
    driver-class-name: com.mysql.jdbc.Driver
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    timeout: 1800000
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: 1
#        max-idle: 5
#        min-idle: 0
#  #配置mapper xml文件的路径
#    mybatis-plus:
#      mapper-locations:
#        classpath: com/imufe/TestSystem/mapper/xml/*.xml

